version: 0.0
os: linux
files:
  - source: flask-app.zip
    destination: /home/ec2-user/
  - source: scripts/
    destination: /home/ec2-user/scripts/

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
